Mayhem Heroes Integration
mayhemheroes/gif-h pull request #1
Opened 2022-05-26 01:01 UTC by capuanob

2022-07-27 07:22 UTC, xansec requested changes
Please make the requested changes.

2022-07-27 07:22 UTC, xansec commented on Dockerfile
> +# Build Stage
Please note that corpus has been renamed to testsuite. Also, you don't need to run git clone here.

2022-07-27 07:22 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/capuanob/gifh-fuzz:latest
Tests -> testsuite. You may omit the image name.

2022-07-27 07:22 UTC, xansec commented on fuzz.cc
> +#include <cstdio> // FILE, fmemopen
Can we rename this to indicate what's being fuzzed?

2022-07-27 07:22 UTC, xansec commented on gif.h
>      bool firstFrame;
Why do we include this in the existing gif.h header? Can we create a separate header to store fuzzer specific function calls?

2022-07-29 17:22 UTC, capuanob commented
@xansec I have made the requested changes, and look forward to your feedback!

2022-08-01 15:42 UTC, xansec requested changes
Please make the requested changes.

2022-08-01 15:42 UTC, xansec commented on gif.h
>      bool firstFrame;
Double check your formatting - this file is still showing up as modified...

2022-08-02 05:43 UTC, xansec approved these changes
I was able to get the header out of the PR. Merging. LGTM!

2022-08-02 05:44 UTC, merged